### ISSUE TITLE
Add include directories to libraries in cmake

### ISSUE THREAD

**Issue by ccvelandres** [lexbor/lexbor#110]
Correct me if I'm wrong but it seems when built with cmake, the headers are not included to the libraries with target_include_directories. This makes self contained builds with cmake using target_link_library(${TARGET} lexbor) to fail since the include directories for the headers are not configured. This can be fixed by adding include_directory to the source/ folder but I think it'll be better to add it to the library.

I suggest to add the include directories to the libraries with target_include_directories(lib PUBLIC ...)

**Comment by lexborisov** [comment]
Hi @ccvelandres 

I will try to fix it soon.
Thanks for the report!

**Comment by Kamrulhasan12345** [comment]
Sorry to bother, but has it been fixed?

**Comment by vtorri** [comment]
because of the situation between Russia and Ukraine, it seems that @lexborisov has no time (or doesn't want) to develop on lexbor for now.

**Comment by lexborisov** [comment]
> because of the situation between Russia and Ukraine, it seems that @lexborisov has no time (or doesn't want) to develop on lexbor for now.

Sorry for my google english :)

Not certainly in that way.
After the start of a special military operation, I was forced to quit (I worked for a BIG American company), I was offered to move to the USA or quit. I refused to move to the USA.
A special military operation has no effect on us ordinary people in Russia. How we lived is how we live. I lost my job - well, well, they decided for me.
I decided to pause and think, rest.
Russians are now, for some reason, not loved, and everything connected with us.
I'm out of politics, I'm just a developer who was fired, deprived of income for my family, and I decided to take a break.
From September 1, I will begin to actively develop this project.
The only thing that stops me is the thought that the world has gone mad. And it is not clear how to promote my project, because I am Russian - which I am very proud of.

**Comment by lexborisov** [comment]
@vtorri  @Kamrulhasan12345 

^^^

**Comment by vtorri** [comment]
Let's see if @lexborisov will update the code soon

**Comment by lexborisov** [comment]
@ccvelandres 

Thanks for the report!
Fixed.
