### ISSUE TITLE
Calling "any other end tag" after "adoption agency algorithm"

### ISSUE THREAD

**Issue by stasoid** [lexbor/lexbor#186]
I am trying to figure out how to properly call `any_other_end_tag` after `adoption_agency_algorithm`, see [whatwg issue 9559](https://github.com/whatwg/html/issues/9559). While doing so I noticed that all the calls to `any_other_end_tag` after `adoption_agency_algorithm` are commented out in lexbor, see for example [here][1]. Why is that? Were there any problems with that code?

[1]: https://github.com/lexbor/lexbor/blob/179309054cf7a6792d76433f60771a029539fb32/source/lexbor/html/tree/insertion_mode/in_body.c#L938

**Comment by lexborisov** [comment]
Hi @stasoid 

The `lxb_html_tree_adoption_agency_algorithm()` function is used for tag `A` and `NOBR`, and closing tags `a`, `b`, `big`, `code` and so on.
As far as I remember for open tags (`A` and `NOBR`) there can be no situation when `lxb_html_tree_adoption_agency_algorithm()` function returns true.

For closing tags, this can be the situation.

Perhaps you should uncomment this code to comply with the specifications. But as far as I know it won't affect anything, the tests will be passed successfully. 
That's the first thing that came to mind. Maybe there's some other catch.

**Comment by stasoid** [comment]
Sorry, this is weird, but may I ask how did you get notified of new messages on the https://github.com/whatwg/html/issues/9559 issue? Did you subscribe to that issue, or is it some other mechanism?

**Comment by lexborisov** [comment]
Hi @stasoid 

It's a normal question — don't worry.
I'm subscribed to all the repositories related to HTML, CSS, URLs, Unicode, and so on; I read all the messages and commits. I try to stay up to date.
It’s hard.

Unfortunately, I can’t work on my project full-time; development on Lexbor is often put on hold for half a year — sometimes even longer — because I have a family and a day job that pays the bills. Lexbor doesn’t bring in any income — just bills for the server and other expenses.
However, fixing bugs and other issues is always a priority for me. These are addressed immediately, with the highest priority. The same goes for ensuring compliance with the specifications.

I'd like to be more involved in the HTML/CSS communities and so on, but as I mentioned above—I can't be in two places at once :)

I wonder why that caught your interest?

**Comment by stasoid** [comment]
Wow, you're actually subscribed to *everything*... That's impressive.

It has caught my interest because I wanted to be sneaky - I didn't want to tell you anything, and add this example to html5lib tests, and when you finally would find out about this after pulling latest html5lib tests, I would react with this image:

<img width="549" height="308" alt="Image" src="https://github.com/user-attachments/assets/4f7238b7-5d89-4655-926f-22edd105d535" />

But you turned out to be too *dexterous* :).

**Comment by lexborisov** [comment]
Hi @stasoid  @sirreal 

Thank you for such an investigation and for your help!
