### ISSUE TITLE
[Feature request] Modification of URLs

### ISSUE THREAD

**Issue by kocsismate** [lexbor/lexbor#249]
I'm currently working on an RFC to use Lexbor for parsing and manipulating URLs in PHP (https://wiki.php.net/rfc/url_parsing_api), and I realized during implementation that Lexbor doesn't support the modification of the URL components once they are parsed. This feature would be very useful to have, so I think the best would be to implement upstream.

For comparison, ADA URL supports this feature: https://cpp-api.ada-url.com/#autotoc_md18

**Comment by lexborisov** [comment]
Hi @kocsismate 

It's not hard to add. This weekend I plan to commit the changes related to URL parsing performance (to be faster than ADA).
After that I can add API for object manipulation.

**Comment by kocsismate** [comment]
@lexborisov That's very kind of you, thank you! I'll incorporate your changes ASAP.

Actually, I was also about to have a look at implementing the feature myself, but it would surely need quite some investigation first on my end, as I'm not that familiar with the internals yet. So I'm happy if you have capacity for the request.

P.S. I created a very basic benchmark comparing Lexbor, PHP's proprietary URL parsing implementation, and uriparser. The actual results can be seen on the lines marked with green: https://github.com/php/php-src/actions/runs/10550036054/job/29225746422?pr=14461#step:14:174 There is another benchmark above for a very basic URL where Lexbor is around 3.5 times slower than PHP's native implementation. As far as I remember from last year, ADA also had similar results (although with quite different implementation of the PHP binding).

I know the results are not directly comparable because of the different requirements due to the different specifications, but at least we have some numbers against which we can compare your changes. :)

**Comment by lexborisov** [comment]
@kocsismate 

## Preamble

I've optimized the URL parsing. It cost almost nothing to organize fast and slow paths in the code.
I can still optimize parsing of domain name, path and so on, but I don't see the point.

And I don't see the point in it because I don't understand what tasks need wild URL parsing speeds?

I compared the result with the ADA URL parser (I was told it was the fastest). Without resorting to wild optimizations in the lexbor project, I was completely satisfied with the result.

Below the text is a comparison of `lexbor URL parser` and `ADA URL parser`.



## URL list

| ID | URL |
|---|:---|
| 0 | `https://example.com` | 
| 1 | `https://it.a.long.domain.name.just.made.up.com` | 
| 2 | `https://пример.рф` | 
| 3 | `https://пример.домена.который.юникод.тестирует.рф` |
| 4 | `https://example.com/my` | 
| 5 | `https://example.com/my/home/in/this/world/is/the/best/place/I/love/and/always/come/back/to` |
| 6 | `https://example.com/Ensure_the_combination_of_parser/serializer/and/API_guarantee_idempotence/For_example/a_non_failure_result_of_a/parse_then_serialize/operation_will_not_change/with_any_further/parse_then_serialize/operations_applied_to_it/Similarly/manipulating_a_non_failure_result_through_the_API/will_not_change_from_applying_any_number/of_serialize_then_parse/operations_to_it` | 
| 7 | `https://example.com/my/../home` | 
| 8 | `https://example.com/my/../home/./in/./this/world/../is/../the/best/./place/../I/./love/../and/always/../come/back/../to` | 
| 9 | `https://example.com/%D0%A4/%D0%AF/%D0%99` | 
| 10 | `https://example.com/%D0%A2%D0%B0%D0%BA/%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B8%D0%BB%D0%B0/%D0%B2/%D0%B8%D1%8E%D0%BB%D0%B5/1805/%D0%B3%D0%BE%D0%B4%D0%B0/%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D0%B0%D1%8F/%D0%90%D0%BD%D0%BD%D0%B0/%D0%9F%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0/%D0%A8%D0%B5%D1%80%D0%B5%D1%80%2C/%D1%84%D1%80%D0%B5%D0%B9%D0%BB%D0%B8%D0%BD%D0%B0/%D0%B8/%D0%BF%D1%80%D0%B8%D0%B1%D0%BB%D0%B8%D0%B6%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F/%D0%B8%D0%BC%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B/%D0%9C%D0%B0%D1%80%D0%B8%D0%B8/%D0%A4%D0%B5%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%BD%D1%8B%2C/%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87%D0%B0%D1%8F/%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE%D0%B3%D0%BE/%D0%B8/%D1%87%D0%B8%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE/%D0%BA%D0%BD%D1%8F%D0%B7%D1%8F/%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D1%8F%2C/%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%B3%D0%BE/%D0%BF%D1%80%D0%B8%D0%B5%D1%85%D0%B0%D0%B2%D1%88%D0%B5%D0%B3%D0%BE/%D0%BD%D0%B0/%D0%B5%D0%B5/%D0%B2%D0%B5%D1%87%D0%B5%D1%80` | 
| 11 | `https://example.com/мой/дом/моя/крепость` | 
| 12 | `https://example.com/Так/говорила/в/июле/1805/года/известная/Анна/Павловна/Шерер/фрейлина/и/приближенная/императрицы/Марии/Феодоровны/встречая/важного/и/чиновного/князя/Василия/первого/приехавшего/на/ее/вечер` |
| 13 | `https://example.com/my/дом/is/my/крепость` | 

## Result

Parsing repetitions for each URL: 100000
Number of repetitions to identify average and median values: 10

| URL ID | Lexbor Average | ADA Average | Lexbor Median | ADA Median |
|---|:---:|:---:|:---:|:---:|
| 0 | 0.016228 | 0.014519 | 0.014263 | 0.012096 |
| 1 | 0.021192 | 0.011828 | 0.021203 | 0.011850 |
| 2 | 0.032634 | 0.060687 | 0.032390 | 0.060640 |
| 3 | 0.105112 | 0.24110 | 0.105268 | 0.241082 |
| 4 | 0.014445 | 0.013445 | 0.014411 | 0.013428 |
| 5 | 0.018582 | 0.014836 | 0.018538 | 0.014842 |
| 6 | 0.032811 | 0.027613 | 0.032939 | 0.027588 |
| 7 | 0.015834 | 0.016519 | 0.015749 | 0.016607 |
| 8 | 0.031256 | 0.043055 | 0.031213 | 0.043161 |
| 9 | 0.016267 | 0.018239 | 0.016279 | 0.018159 |
| 10 | 0.116674 | 0.107119 | 0.117256 | 0.106831 |
| 11 | 0.025567 | 0.056733 | 0.025793 | 0.056756 |
| 12 | 0.122021 | 0.296652 | 0.123431 | 0.296686 |
| 13 | 0.024461 | 0.048586 | 0.024380 | 0.048411 |

## Hardware

Apple M1 Pro chip, 10-core CPU with 8 performance cores and 2 efficiency cores, 16GB.
OS 14.6.1 (23G93)

## Compilation options

For Lexbor and Ada
```
-O2 -Wall -pedantic -pipe -fPIC
```

P.S.: I could get steamed up and completely tear apart ADA Parser, but I don't see the point, it's not a place where you need to spend a lot of effort on micro-optimizations.

I'll try these tests on an Intel processor a little later.

**Comment by lexborisov** [comment]
@kocsismate 

Also, if I'm not mistaken, ADA doesn't validate URLs, i.e. it doesn't log errors. And this imposes a lot of restrictions on code optimization, you have to do a lot of different checks and logging of parsing.

I mean this: [https://url.spec.whatwg.org/#writing](https://url.spec.whatwg.org/#writing)
For an example, see [path state](https://url.spec.whatwg.org/#path-state) paragraph `2.1` and `2.2`. And there are enough such checks in the code, they make optimization very difficult.

Lexbor parser always validates URL data and saves errors to the log.

**Comment by kocsismate** [comment]
@lexborisov I upgraded the bundled Lexbor, but I found some BC breaks and some other problems:
- `-Werror=int-conversion` was triggered: https://github.com/php/php-src/actions/runs/11210426284/job/31157304027?pr=14461#step:10:8
- Member access within null pointer error was triggered, so I had to conditionally destroy the idna member in the parser struct: I changed `lxb_unicode_idna_destroy(&parser->idna, false);` to `if (parser->idna != NULL) {lxb_unicode_idna_destroy(&parser->idna, false);}` (sorry, somehow I could not link this diff on GitHub)
- There are some port related test failures which I had to fix with https://github.com/php/php-src/pull/14461/commits/da184a6df579ce0b9791af70a24bc5b49f6ac947#diff-618caf650d8fa6adab7f8c7f92226c7708633f760d82b85aa58e43383c332f96R123. Apparently, the `has_port` field does not have an effect and I explicitly have to check for the `0` port value. I don't know if it's intentional, but I wanted to point this out.
- Some tests now fail due to the path component being different, but I guess my changes are to blame (https://github.com/php/php-src/pull/14461/commits/da184a6df579ce0b9791af70a24bc5b49f6ac947#diff-618caf650d8fa6adab7f8c7f92226c7708633f760d82b85aa58e43383c332f96L136). I'll have another look at those again...

Regarding performance: Lexbor is much faster now indeed. Using GitHub runners for benchmarking surely won't provide reliable data, but at least we have an estimation
- for `example.com`, Lexbor used to finish in `0.000931104`. Now it's `0.000327715`.
- for `https://username:password@www.google.com:8080/pathname1/pathname2/pathname3?query=true#hash-exists`, Lexbor used to finish in `0.001555342`. Now it's `0.000800032`.

**Comment by lexborisov** [comment]
Hi @kocsismate 

1. Ok, I'll fix it.
2. Here the correct solution is: `parser->idna = lxb_unicode_idna_destroy(parser->idna, true);` Inside the lxb_unicode_idna_destroy() function there is a check for NULL. I'll make a patch for it now.
3. I'll look at it, all right.
4. Yes, now a patch is just a string that is already ready to be “consumed”, it contains a “/” at the beginning.

As for performance, I can still increase it significantly, but I just don't see the point. Well, parsing URLs is not worth such optimization efforts.

**Comment by nielsdos** [comment]
@lexborisov Just wanted to say that the first point is not in your code. This is because we have a modified structure in our bundled fork and our modified Python code generation script wasn't re-run. So you can ignore the first point.

**Comment by lexborisov** [comment]
@kocsismate 

I think you haven't updated the code for the Unicode module.  Do you have a NULL check in the [lxb_unicode_idna_destroy() function](https://github.com/lexbor/lexbor/blob/master/source/lexbor/unicode/idna.c#L97)?

**Comment by kocsismate** [comment]
Oh yes, you are right! I didn't have it until now... Thanks for the idea!

**Comment by lexborisov** [comment]
@kocsismate 

A bit delayed, but the functions to change URLs have been added. Please, see https://github.com/lexbor/lexbor/blob/master/source/lexbor/url/url.h#L339

**Comment by kocsismate** [comment]
@lexborisov Thank you, this is awesome news! I'll have a look ASAP.

**Comment by kocsismate** [comment]
I tried the new functions, and they work well for me based on the tests I have! Thank you again very much!
